Added inverted index
ekifel/go-core pull request #3
Opened 2021-05-23 19:55 UTC by ekifel

Задача №1.
Создать обратный индекс для документов. Разместить индекс в пакете «index». Ключом индекса будет каждое слово из описания ссылок, значением – номер документа.
После сканирования сайтов все найденные ссылки должны храниться в виде структуры следующего вида:

```
// Document - документ, веб-страница, полученная поисковым роботом.
type Document struct {
    ID    int
    URL   string
    Title string
}
```

Проиндексированные документы должны храниться в массиве документов и объекте из пакета «index». При этом для каждого документа нужно добавить его номер – поле в структуре данных вместе с URL и Title.
Массив документов должен быть отсортирован по номерам, используя сортировку из стандартной библиотеки.

Задача №2.
Переделать метод поисковой выдачи на использование индекса.
Для поиска по индексу приложение должно импортировать поисковый индекс из пакета «index» как зависимость и искать по индексу, а не по массиву документов. Поиск по индексу должен выдавать номера документов (поле в структуре данных документа).

Задача №3.
После получения номеров документов из индекса нужно использовать бинарный поиск по отсортированному ранее массиву документов (по номерам документов).
Можно воспользоваться стандартной библиотекой или написать свою реализацию.

2021-05-23 21:39 UTC, DmitriyVTitov requested changes
Всё бы хорошо, но такой конструктор принять не могу!

2021-05-23 21:39 UTC, DmitriyVTitov commented on gosearch/cmd/gosearch/main.go
> +	index.New()
Функция-конструктор New() должна возвращать объект, а не инициализировать уже созданный. Конструктор создаёт объект, а не является методом уже созданного.

2021-05-23 21:39 UTC, DmitriyVTitov commented on gosearch/pkg/index/index.go
> +func (i *Index) New() {
i - традиционно счётчик цикла, поэтому я бы назвал `ind`

2021-05-23 21:39 UTC, DmitriyVTitov commented on gosearch/pkg/index/index.go
> +func (i *Index) indexExists(key string, j int) bool {
имена неудачные: i, j - счётчики цикла и ни о чём не говорят.
`i` -> `ind`, `j` -> `id`

2021-05-23 21:39 UTC, DmitriyVTitov commented on gosearch/pkg/index/index.go
> +}
Вот это недоразумение нужно исправить. Я, как пользователь пакета, не должен создавать какие-то переменные и думать какой метод нужно вызвать чтобы начать работать. Я должен вызвать функцию конструктор, которая всё сделает и вернёт мне нужный объект.

2021-05-23 21:39 UTC, DmitriyVTitov commented on gosearch/pkg/index/index.go
> +func (i *Index) New() {
да и вообще: функция, которая ничего не принимает и ничего не возвращает - почти всегда ошибка проектирования

2021-05-23 22:07 UTC, ekifel commented on gosearch/pkg/index/index.go
> +}
Согласен, ерунда какую-то сделал, перемкнуло. Конструктор исправил

2021-05-24 18:27 UTC, DmitriyVTitov approved these changes
ОК

2021-05-24 18:27 UTC, DmitriyVTitov commented on gosearch/pkg/index/index.go
> +}
возьмите за правило комментировать все экспортируемые объекты

2021-05-28 05:21 UTC, merged